stages:
  - lint


# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
cache:
  paths:
    - .cache/pip

linting:
  stage: lint
  image: python:3.9.15
  script:
    - pip install pre-commit==3.5.0
    - pip install jupyter_contrib_nbextensions
    - pip install notebook==6.4.12
    - pre-commit run pipelines/. notebooks/. strava/.
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - when: always
  needs: []
