exclude: '^(build|docs|eventclf/eventclf/v1|eventclf/build)'

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-json
      - id: check-merge-conflict
      - id: check-xml
      - id: check-yaml
      - id: check-toml
      - id: debug-statements
      - id: end-of-file-fixer
        exclude: .*\.json

  - repo: https://github.com/ambv/black
    rev: 23.11.0
    hooks:
      - id: black

  - repo: http://github.com/timothycrosley/isort
    rev: 5.13.0
    hooks:
      - id: isort
        additional_dependencies: ["toml"]
        args: ["--profile", "black", "--filter-files"]

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args: ["--max-line-length=88", '--ignore=E203,E501,W503']

  - repo: local
    hooks:
      - id: jupyter-nb-clear-output
        name: jupyter-nb-clear-output
        files: \.ipynb$
        stages: [commit]
        language: system
        entry: jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace
